# Generated by Django 5.0.1 on 2024-01-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
