# Generated by Django 5.0.1 on 2024-01-31 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.komentar'),
        ),
    ]
