# Generated by Django 5.0.1 on 2024-02-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_komentar_replay_replaykomentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='news.news'),
        ),
        migrations.AlterField(
            model_name='replaykomentar',
            name='komentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='news.komentar'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='news.news')),
            ],
        ),
    ]
