# Generated by Django 5.0.1 on 2024-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('no_telphon', models.CharField(max_length=100)),
                ('jenis_kelamain', models.TextField()),
                ('pekerjaan', models.TextField()),
            ],
        ),
    ]
