# Generated by Django 5.0.1 on 2024-02-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosialmedia',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
